### PR TITLE
Releasing v5.3.2

### PR DESCRIPTION
**Pull request by mzikherman**
(I've already published to Rubygems).

### CODE REVIEW

**Comment by dblock** [comment]
You can just commit these when making a release @mzikherman. Thanks for taking care of that!

**Comment by mzikherman** [comment]
I have the Rubygems permission to publish it but I don't think I'm a collab on this repo in GitHub (I didn't have the right creds to push upstream).

**Comment by dblock** [comment]
You were invited, just never accepted, go to https://github.com/mongoid/mongoid-slug/invitations.

**Comment by mzikherman** [comment]
Ah, just did it, thanks for helping out this open source n00b @dblock

**Comment by dblock** [comment]
Check email spam too for next time.

**Pull request merged**
