### PR TITLE
Remove deprecated alias_method_chain

### LINKED ISSUE #232: [Rails 5 Deprecation] alias_method_chain is deprecated
The method is used there:

https://github.com/mongoid/mongoid-slug/blob/46b5f5e1e8f917c8975ddd1339ed21eb48c2f4eb/lib/mongoid/slug/paranoia.rb#L16

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at [path]/config/environment.rb:5)
```

and is now deprecated. Interesting link about that: http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/

### PR DESCRIPTION
**Pull request by hugoabonizio**
Replace ```alias_method_chain``` with equivalent ```alias_method```. Fix #232 .

### CODE REVIEW

**Comment by dblock** [comment]
The deprecation suggests we use `prepend`. What's the reason not to do this?

**Comment by hugoabonizio** [comment]
@dblock I refactored to use ```Module#prepend```.

**Comment by dblock** [comment]
Great stuff.

**Comment by MajedBojan** [comment]
am cloning one project from the bitbuket am still getting this warning i don't know from where is coming exactly

**Pull request merged**
